name: "run tests"
on:
  [push, pull_request, workflow_dispatch]

jobs:
  perl_tester:
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-latest"
        perl-version: ["5.6", "5.8", "5.10", "5.12", "5.14", "5.16", "5.18", "5.20", "5.22", "5.24", "5.26", "5.28", "5.30", "5.32", "5.34", "5.36", "5.38", "5.40"]
        exclude:
          - { os: ubuntu-latest, perl-version: "5.6" }
          - { os: ubuntu-latest, perl-version: "5.8" }
          - { os: ubuntu-latest, perl-version: "5.10" }
          - { os: ubuntu-latest, perl-version: "5.12" }
          - { os: ubuntu-latest, perl-version: "5.14" }
          - { os: ubuntu-latest, perl-version: "5.16" }

    runs-on: ${{ matrix.os }}
    name: "perl v${{ matrix.perl-version }} on ${{ matrix.os }}"

    steps:
      - uses: actions/checkout@v4
      - name: "Set up perl"
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl-version }}
      - run: cd /usr/include && { h2ph -eal syscall.h sys/random.h || true; }
      - run: perl Makefile.PL
      - run: cpanm --installdeps --with-develop --notest .
      - run: make test
